package com.elik745i.isobotbt

data class RobotCommand(
    val index: Int,
    val codeName: String,
    val label: String,
    val category: CommandCategory,
)

enum class CommandCategory(val title: String) {
    ALL("All"),
    MOVEMENT("Movement"),
    COMBAT("Combat"),
    SOCIAL("Social"),
    SHOWCASE("Showcase"),
}

object RobotCommands {
    val all = listOf(
        RobotCommand(0, "forward", "Forward", CommandCategory.MOVEMENT),
        RobotCommand(1, "backward", "Backward", CommandCategory.MOVEMENT),
        RobotCommand(2, "sideright", "Side Right", CommandCategory.MOVEMENT),
        RobotCommand(3, "sideleft", "Side Left", CommandCategory.MOVEMENT),
        RobotCommand(4, "fleft", "Forward Left", CommandCategory.MOVEMENT),
        RobotCommand(5, "fright", "Forward Right", CommandCategory.MOVEMENT),
        RobotCommand(6, "bleft", "Backward Left", CommandCategory.MOVEMENT),
        RobotCommand(7, "bright", "Backward Right", CommandCategory.MOVEMENT),
        RobotCommand(8, "fclockwise", "Forward Clockwise", CommandCategory.MOVEMENT),
        RobotCommand(9, "fcounter", "Forward Counter", CommandCategory.MOVEMENT),
        RobotCommand(10, "bclockwise", "Backward Clockwise", CommandCategory.MOVEMENT),
        RobotCommand(11, "bcounter", "Backward Counter", CommandCategory.MOVEMENT),
        RobotCommand(12, "headleft", "Head Left", CommandCategory.MOVEMENT),
        RobotCommand(13, "headright", "Head Right", CommandCategory.MOVEMENT),
        RobotCommand(14, "leanforward", "Lean Forward", CommandCategory.MOVEMENT),
        RobotCommand(15, "leanback", "Lean Back", CommandCategory.MOVEMENT),
        RobotCommand(16, "lpunch", "Left Punch", CommandCategory.COMBAT),
        RobotCommand(17, "r12", "Right 12", CommandCategory.COMBAT),
        RobotCommand(18, "lchop", "Left Chop", CommandCategory.COMBAT),
        RobotCommand(19, "sidechopl", "Side Chop Left", CommandCategory.COMBAT),
        RobotCommand(20, "combopunch", "Combo Punch", CommandCategory.COMBAT),
        RobotCommand(21, "rpunch", "Right Punch", CommandCategory.COMBAT),
        RobotCommand(22, "rchop", "Right Chop", CommandCategory.COMBAT),
        RobotCommand(23, "l12", "Left 12", CommandCategory.COMBAT),
        RobotCommand(24, "sidechopr", "Side Chop Right", CommandCategory.COMBAT),
        RobotCommand(25, "lbackhand", "Left Backhand", CommandCategory.COMBAT),
        RobotCommand(26, "doublechop", "Double Chop", CommandCategory.COMBAT),
        RobotCommand(27, "doublebackhand", "Double Backhand", CommandCategory.COMBAT),
        RobotCommand(28, "slapping", "Slapping", CommandCategory.COMBAT),
        RobotCommand(29, "rbackhand", "Right Backhand", CommandCategory.COMBAT),
        RobotCommand(30, "upperchop", "Upper Chop", CommandCategory.COMBAT),
        RobotCommand(31, "roundhousel", "Roundhouse Left", CommandCategory.COMBAT),
        RobotCommand(32, "roundhouser", "Roundhouse Right", CommandCategory.COMBAT),
        RobotCommand(33, "forwardkickl", "Forward Kick Left", CommandCategory.COMBAT),
        RobotCommand(34, "forwardkickr", "Forward Kick Right", CommandCategory.COMBAT),
        RobotCommand(35, "sidekickl", "Side Kick Left", CommandCategory.COMBAT),
        RobotCommand(36, "roundhouselr", "Roundhouse LR", CommandCategory.COMBAT),
        RobotCommand(37, "forwardkicklr", "Forward Kick LR", CommandCategory.COMBAT),
        RobotCommand(38, "combokick", "Combo Kick", CommandCategory.COMBAT),
        RobotCommand(39, "sidekickr", "Side Kick Right", CommandCategory.COMBAT),
        RobotCommand(40, "backkickl", "Back Kick Left", CommandCategory.COMBAT),
        RobotCommand(41, "backkickr", "Back Kick Right", CommandCategory.COMBAT),
        RobotCommand(42, "highkickl", "High Kick Left", CommandCategory.COMBAT),
        RobotCommand(43, "highkickr", "High Kick Right", CommandCategory.COMBAT),
        RobotCommand(44, "splits1", "Splits 1", CommandCategory.COMBAT),
        RobotCommand(45, "guardl", "Guard Left", CommandCategory.COMBAT),
        RobotCommand(46, "guardr", "Guard Right", CommandCategory.COMBAT),
        RobotCommand(47, "doubleguard1", "Double Guard 1", CommandCategory.COMBAT),
        RobotCommand(48, "doubleguard2", "Double Guard 2", CommandCategory.COMBAT),
        RobotCommand(49, "dodgel", "Dodge Left", CommandCategory.COMBAT),
        RobotCommand(50, "dodger", "Dodge Right", CommandCategory.COMBAT),
        RobotCommand(51, "duck", "Duck", CommandCategory.COMBAT),
        RobotCommand(52, "swayback", "Sway Back", CommandCategory.COMBAT),
        RobotCommand(53, "upblock", "Up Block", CommandCategory.COMBAT),
        RobotCommand(54, "splits2", "Splits 2", CommandCategory.COMBAT),
        RobotCommand(55, "comboblock", "Combo Block", CommandCategory.COMBAT),
        RobotCommand(56, "zero", "Zero", CommandCategory.SOCIAL),
        RobotCommand(57, "homeposition", "Home Position", CommandCategory.MOVEMENT),
        RobotCommand(58, "soundoff", "Sound Off", CommandCategory.SOCIAL),
        RobotCommand(59, "affirm", "Affirm", CommandCategory.SOCIAL),
        RobotCommand(60, "disagree", "Disagree", CommandCategory.SOCIAL),
        RobotCommand(61, "goodmorning", "Good Morning", CommandCategory.SOCIAL),
        RobotCommand(62, "greet1", "Greet 1", CommandCategory.SOCIAL),
        RobotCommand(63, "greet2", "Greet 2", CommandCategory.SOCIAL),
        RobotCommand(64, "greet3", "Greet 3", CommandCategory.SOCIAL),
        RobotCommand(65, "greet4", "Greet 4", CommandCategory.SOCIAL),
        RobotCommand(66, "bye1", "Bye 1", CommandCategory.SOCIAL),
        RobotCommand(67, "bye2", "Bye 2", CommandCategory.SOCIAL),
        RobotCommand(68, "bye3", "Bye 3", CommandCategory.SOCIAL),
        RobotCommand(69, "bye4", "Bye 4", CommandCategory.SOCIAL),
        RobotCommand(70, "bye5", "Bye 5", CommandCategory.SOCIAL),
        RobotCommand(71, "respect", "Respect", CommandCategory.SOCIAL),
        RobotCommand(72, "thanks1", "Thanks 1", CommandCategory.SOCIAL),
        RobotCommand(73, "thanks2", "Thanks 2", CommandCategory.SOCIAL),
        RobotCommand(74, "love1", "Love 1", CommandCategory.SOCIAL),
        RobotCommand(75, "love2", "Love 2", CommandCategory.SOCIAL),
        RobotCommand(76, "love3", "Love 3", CommandCategory.SOCIAL),
        RobotCommand(77, "standupfront", "Stand Up Front", CommandCategory.SHOWCASE),
        RobotCommand(78, "standupback", "Stand Up Back", CommandCategory.SHOWCASE),
        RobotCommand(79, "excited1", "Excited 1", CommandCategory.SOCIAL),
        RobotCommand(80, "excited2", "Excited 2", CommandCategory.SOCIAL),
        RobotCommand(81, "excited3", "Excited 3", CommandCategory.SOCIAL),
        RobotCommand(82, "excited4", "Excited 4", CommandCategory.SOCIAL),
        RobotCommand(83, "party", "Party", CommandCategory.SHOWCASE),
        RobotCommand(84, "amazed", "Amazed", CommandCategory.SOCIAL),
        RobotCommand(85, "regret1", "Regret 1", CommandCategory.SOCIAL),
        RobotCommand(86, "regret2", "Regret 2", CommandCategory.SOCIAL),
        RobotCommand(87, "regret3", "Regret 3", CommandCategory.SOCIAL),
        RobotCommand(88, "worry", "Worry", CommandCategory.SOCIAL),
        RobotCommand(89, "pain1", "Pain 1", CommandCategory.SOCIAL),
        RobotCommand(90, "pain2", "Pain 2", CommandCategory.SOCIAL),
        RobotCommand(91, "beg1", "Beg 1", CommandCategory.SOCIAL),
        RobotCommand(92, "beg2", "Beg 2", CommandCategory.SOCIAL),
        RobotCommand(93, "merry", "Merry", CommandCategory.SOCIAL),
        RobotCommand(94, "hilarious", "Hilarious", CommandCategory.SOCIAL),
        RobotCommand(95, "hidenseek", "Hide N Seek", CommandCategory.SHOWCASE),
        RobotCommand(96, "youlike", "You Like", CommandCategory.SOCIAL),
        RobotCommand(97, "mystery5", "Mystery 5", CommandCategory.SHOWCASE),
        RobotCommand(98, "tipsy", "Tipsy", CommandCategory.SOCIAL),
        RobotCommand(99, "tickleme", "Tickle Me", CommandCategory.SOCIAL),
        RobotCommand(100, "tiredfeet", "Tired Feet", CommandCategory.SOCIAL),
        RobotCommand(101, "needabreak", "Need A Break", CommandCategory.SOCIAL),
        RobotCommand(102, "wave1", "Wave 1", CommandCategory.SOCIAL),
        RobotCommand(103, "wave2", "Wave 2", CommandCategory.SOCIAL),
        RobotCommand(104, "applause", "Applause", CommandCategory.SOCIAL),
        RobotCommand(105, "mystery6", "Mystery 6", CommandCategory.SHOWCASE),
        RobotCommand(106, "toosexy", "Too Sexy", CommandCategory.SHOWCASE),
        RobotCommand(107, "clink", "Clink", CommandCategory.SOCIAL),
        RobotCommand(108, "relax", "Relax", CommandCategory.SOCIAL),
        RobotCommand(109, "soccer1", "Soccer 1", CommandCategory.SHOWCASE),
        RobotCommand(110, "soccer2", "Soccer 2", CommandCategory.SHOWCASE),
        RobotCommand(111, "soccer3", "Soccer 3", CommandCategory.SHOWCASE),
        RobotCommand(112, "lift", "Lift", CommandCategory.SHOWCASE),
        RobotCommand(113, "countonme", "Count On Me", CommandCategory.SOCIAL),
        RobotCommand(114, "articulation", "Articulation", CommandCategory.SHOWCASE),
        RobotCommand(115, "showoff1", "Show Off 1", CommandCategory.SHOWCASE),
        RobotCommand(116, "showoff2", "Show Off 2", CommandCategory.SHOWCASE),
        RobotCommand(117, "showoff3", "Show Off 3", CommandCategory.SHOWCASE),
        RobotCommand(118, "showoff4", "Show Off 4", CommandCategory.SHOWCASE),
        RobotCommand(119, "cominthrough", "Comin Through", CommandCategory.SHOWCASE),
        RobotCommand(120, "catch", "Catch", CommandCategory.SHOWCASE),
        RobotCommand(121, "randomperformance2", "Random Performance 2", CommandCategory.SHOWCASE),
        RobotCommand(122, "western", "Western", CommandCategory.SHOWCASE),
        RobotCommand(123, "giantrobot", "Giant Robot", CommandCategory.SHOWCASE),
        RobotCommand(124, "tropicaldance", "Tropical Dance", CommandCategory.SHOWCASE),
        RobotCommand(125, "randomanimal", "Random Animal", CommandCategory.SHOWCASE),
        RobotCommand(126, "randomperformance1", "Random Performance 1", CommandCategory.SHOWCASE),
        RobotCommand(127, "airguitar", "Air Guitar", CommandCategory.SHOWCASE),
        RobotCommand(128, "airdrum", "Air Drum", CommandCategory.SHOWCASE),
        RobotCommand(129, "exercises", "Exercises", CommandCategory.SHOWCASE),
        RobotCommand(130, "headstandexercises", "Headstand Exercises", CommandCategory.SHOWCASE),
        RobotCommand(131, "forwardsomersault", "Forward Somersault", CommandCategory.SHOWCASE),
        RobotCommand(132, "mystery4", "Mystery 4", CommandCategory.SHOWCASE),
        RobotCommand(133, "mystery3", "Mystery 3", CommandCategory.SHOWCASE),
        RobotCommand(134, "mystery2", "Mystery 2", CommandCategory.SHOWCASE),
        RobotCommand(135, "mystery1", "Mystery 1", CommandCategory.SHOWCASE),
        RobotCommand(136, "pose3", "Pose 3", CommandCategory.SHOWCASE),
        RobotCommand(137, "pose2", "Pose 2", CommandCategory.SHOWCASE),
        RobotCommand(138, "pose1", "Pose 1", CommandCategory.SHOWCASE),
    )

    val quick = listOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11).map { index -> all.first { it.index == index } }

    fun filter(query: String, category: CommandCategory): List<RobotCommand> {
        val normalizedQuery = query.trim().lowercase()
        return all.filter { command ->
            val categoryMatches = category == CommandCategory.ALL || command.category == category
            val queryMatches = normalizedQuery.isBlank() ||
                command.label.lowercase().contains(normalizedQuery) ||
                command.codeName.lowercase().contains(normalizedQuery) ||
                command.index.toString() == normalizedQuery
            categoryMatches && queryMatches
        }
    }
}